
[window]
opacity = 0.96
[font]
normal = {family = "Iosevka", style = "Regular"}
size = 13
[cursor]
style = {shape = "Block", blinking = "On"}
blink_timeout = 0
blink_interval = 750
unfocused_hollow = false
[mouse]
hide_when_typing = true
[colors]
cursor = {text = "0x000000", cursor = "#ff7eb6"}
[env]
TERM = "xterm-256color"

[general]
import = [
	"~/.config/alacritty/oxocarbon.toml"
]
